apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rf46xxu51-nodejs
  janus-idp.io/tekton: rf46xxu51-nodejs
  backstage.io/kubernetes-id: rf46xxu51-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rf46xxu51-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
