apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rf46xxu51-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rf46xxu51-nodejs 
  name: rf46xxu51-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rf46xxu51-nodejs 
